# title: TrroJay's shelter
# author: TrroJay
# subtitle: A frustrated ENFP/INFP who is trying to figure out life.

# url: "https://trrojay.github.io"
# baseurl: "/thoughts"

# footer_only_homepage: true

# profile-picture: assets/profile.png
# favicon_location: assets/favicon.ico

# permalink: /:year-:month-:day-:title/
# sass:
#     style: compressed
#     sass_dir: css

# navbar:
#   - name: "Thoughts"
#     link: "about"

title: "TrroJay's shelter"
author: "TrroJay"
subtitle: "A frustrated ENFP/INFP who is trying to figure out life."

url: "https://trrojay.github.io"
baseurl: "" 

footer_only_homepage: true
profile_picture: "/assets/profile.png"
favicon: "/assets/favicon.ico"

permalink: /:year-:month-:day-:title/

sass:
  style: compressed
  sass_dir: _sass  # 更标准的目录名

navigation:
  - title: "Thoughts"
    url: "/about/"