title: TrroJay's sHeLTer
author: TrroJay
subtitle: 

baseurl: ""

footer_only_homepage: true
footer_url: "https://music.163.com/#/song?id=486194136"
footer_text: "Thanks for tickling my brain!"


profile_picture: "/assets/profile.png"
favicon: "/assets/favicon.ico"

permalink: /:year-:month-:day-:title/

sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Thoughts"
   link: "thoughts"
