title: TrroJay's shelter
author: TrroJay
subtitle: A frustrated ENFP/INFP who is trying to figure out life.

url: "https://trrojay.github.io"
baseurl: "/thoughts"

footer_only_homepage: true

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Thoughts"
   link: "about"

